config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/about'
  get 'pages/contact'
  root 'listings#index'#sets root file to all listings
  get 'seller' => 'listings#seller' #creates a new url at localhost/seller
  get 'sales' => "orders#sales" #set up new url for sales to see order history
  get 'purchases' => "orders#purchases" #set up new url for purchases to see order history
  get 'success', to: 'orders#done'
  

  resources :listings do #tell rails to include listing id number in URL for orders pages
  resources :orders, only: [:new, :create] #tells rails that only URLS it needs to worry about when it comes to orders is for new and create actions
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :orders

    def thumbnail 
        return self.image.variant(resize: "100x100")
    end

    def medium
        return self.image.variant(resize: "200x200")
    end

    def large
        return self.image.variant(resize: "300x300")
    end

    # validates data fields 
    validates :name, :description, :price, :image, presence: true
    validates :price, numericality: {greater_than: 0 }

    belongs_to :user
end

def correct_image_type
    if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:image, 'must be a JPEG or PNG.')
    elsif image.attached? == false
        errors.add(:image, 'must have an image attached')
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    before_action :set_listing, only: [:image, :show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy] #before a user takes these actions, need to authenticate them first by making sure that they are signed in
    before_action :check_user, only: [:edit, :update, :destroy] #no check_user keyword in devise so need to make own function in private at bottom of screen
  
     # When a user wants to go to new seller URL, the listings that they want to see are the same listings as the signed in user and orders them to when they were created in descending order
    def seller
      @listings = Listing.where(user: current_user).order("created_at DESC")
    end

    # GET /listings
    # GET /listings.json
    # Display all Listings
    def index
      @listings = Listing.all.order("created_at DESC")
    end
  
    # GET /listings/1
    # GET /listings/1.json
    def show
    end
  
    # GET /listings/new
    def new
      @listing = Listing.new
    end
  
    # GET /listings/1/edit
    def edit
      
    end
  
    # POST /listings
    # POST /listings.json
    def create
      @listing = Listing.new(listing_params)
      @listing.user_id = current_user.id #Devise uses helpful keyword current_user which is getting current user and setting it to the id of the current listing
      
      respond_to do |format|
        if @listing.save
          format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
          format.json { render :show, status: :created, location: @listing }
        else
          format.html { render :new }
          format.json { render json: @listing.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /listings/1
    # PATCH/PUT /listings/1.json
    def update
      respond_to do |format|
        if @listing.update(listing_params)
          format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
          format.json { render :show, status: :ok, location: @listing }
        else
          format.html { render :edit }
          format.json { render json: @listing.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /listings/1
    # DELETE /listings/1.json
    def destroy
      @listing.destroy
      respond_to do |format|
        format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_listing
        @listing = Listing.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def listing_params
        params.require(:listing).permit(:name, :description, :price, :image)
      end

      #checks to see if the current user that is logged in, is the same as the user that created the listing in question
      def check_user
        if current_user != @listing.user
          redirect_to root_url, alert: "Sorry, this listing belongs to someone else" 
        end
      end
  end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing, url: listings_path, method: :post do |f| %>
<% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

       <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  </div>
<% end %>

 <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="center">
  <div class="jumbotron">
    <h1> Quality Australian Products! </h1>
    <h2> Shop Directly through Australian manufacturers </h2>
  </div>
  <div class="row">
  <% if Listing.joins(:image_attachment) %>
    <% @listings.each do |listing| %>

      <div class="col-md-3">
        <div class="wrap">
          <div class="thumbnail">
            <% if listing.image.attached? %>
              <%= link_to image_tag(listing.medium), listing %>
            <% end %>
              <div class="caption">
              <h3> <%= listing.name %></h3>
              <p><%= number_to_currency(listing.price) %></p>
              <p><%= "Sold by #{listing.user.name}" %></p>
              <%= link_to 'Show', listing, class: "btn btn-link" %>
              </div><!---caption-->
          </div><!--thumbnail-->
        </div> <!--wrap-->
      </div><!--col-md-3-->
    <% end %>
    <% end %>
  </div><!--row-->
</div> <!--center-->

<div class="center">
  <% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-dark" %> <!---Only signed in users can see link to post a new listing-->
  <% end %>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th>Image</th>
    <th>Name</th> 
    <th>Description</th>
    <th>Price</th>
    <th>Actions</th>
  </tr>

    <% @listings.each do |listing| %>
        <tr>
            <td> <%= image_tag listing.thumbnail %></td>
            <td> <%= listing.name %></td>
            <td> <%= listing.description %></td>
            <td> <%= number_to_currency(listing.price) %></td>
            <td>
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Action
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <li><%= link_to "View", listing, class: "btn btn-link" %> </li>
                    <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
                </div>
            </div>
            </td>
        </tr>
    <% end %>
<table>
    

  <% if user_signed_in? %>
    <%= link_to 'New Listing', new_listing_path, class: "btn btn-dark" %> <!---Only signed in users can see link to post a new listing-->
  <% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= link_to image_tag(@listing.large) %>
    </div> <!-- close thumbnail-->
  </div>
  <div class="col-md-6">
    <h3> <%= @listing.name %> </h3>
    <p> <%= number_to_currency(@listing.price) %> </p>
    <p><%= @listing.description %> </p>
    <br>
      <div>
    <%= link_to "Buy It now", new_listing_order_path(@listing), class: "btn btn-primary" %> <!-- shortcut to tell rails to use id of current listing. -->
      </div> <!-- close center !-->
  </div>
</div>


<!-- if current user is the same person that created the listing than show the edit link, else just show back-->
<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>
<%= link_to 'Destroy', @listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>