config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/about'
  get 'pages/contact'
  root 'listings#index'#sets root file to all listings
  get 'seller' => 'listings#seller' #creates a new url at localhost/seller
  get 'sales' => "orders#sales" #set up new url for sales to see order history
  get 'purchases' => "orders#purchases" #set up new url for purchases to see order history
  get 'success', to: 'orders#done'
  

  resources :listings do #tell rails to include listing id number in URL for orders pages
  resources :orders, only: [:new, :create] #tells rails that only URLS it needs to worry about when it comes to orders is for new and create actions
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
validates :address, :city, :state, presence: true
belongs_to :listing
belongs_to :buyer, class_name: "User"
belongs_to :seller, class_name: "User"
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! #make sure user signed in before they place an order. Devise gives us this special keyword

  #deleted index so users cannot see all orders

  #on sales page, show all orders where seller of order equal to current user. Display as created at, descending.
  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC") 
  end

  #on purchases page, show all orders where buyer of order equal to current user. Display as created at, descending.
  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end

  #deleted show

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id]) 
    Stripe.api_key = ENV["STRIPE_API_KEY"] 

    @stripe_checkout_session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        name: @listing.name,
        description: @listing.description,
        amount: (@listing.price * 100).floor,
        currency: 'aud',
        quantity: 1,
      }],
      success_url: 'http://localhost:3000/success',
      cancel_url: 'http://localhost:3000/cancel',
    )
  end


 #deleted edit

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params) #create new order and pass in parameters from private section below
    @listing = Listing.find(params[:listing_id]) #can find the listing of the id that is being bought in the url
    @seller = @listing.user #the seller of the listing is the same as the user who created the listing
    
    #tells rails how to fill out columns
    @order.listing_id = @listing.id #tell rails how to fill in order listing id in datasbase with the listing id
    @order.buyer_id = current_user.id #Tells rails to fil out the buyer id column in the database with the current user id
    @order.seller_id = @seller.id #Tells rails to fill out seller id coluumn in the database


    respond_to do |format|
        if @order.save
        format.html { redirect_to root_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
        else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
        end
    end
  end

 #deleted update and destroy

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
  end

  def done

  end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row">
    <div class="col-md-4">
      <div class="thumbnail">
        <%= link_to image_tag (@listing.large) %>
      </div> <!--thumbnail-->
    </div> <!--col-md-4-->
    <div class="col-md-8">
      <%= form_for([@listing, @order]) do |form| %> <!-- rails can see that the listing is a type of listing and an order is a type order so will plug in the correct route to save the data-->
      <% if @order.errors.any? %>
      <div id="error_explanation" class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

        <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :city %>
      <%= form.text_field :city, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :state %>
      <%= form.text_field :state, class: "form-control" %>
    </div>

  <!-- Fields for users to input credit card number and CVC -->
  <div class="form-group">
      <div class="row">
        <div class="col-md-8">
          <%= label_tag :card_number, "Credit Card Number" %>
          <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
        </div>
        <div class="col-md-4">
          <%= label_tag :card_code, "CVC" %>
          <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= label_tag nil, "Expiration Date" %>
      <div class="row">
      <!-- Use rails key word select_month to create dropdown menu and to display as two digit numbers -->
        <div class="col-md-3">
          <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
        </div>
        <!-- Use rails key word select_year to crate a drop down and can select start year from today and end year in 10 years -->
        <div class="col-md-3">
          <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= form.submit "Complete Order", class: "btn btn-success" %>
    </div>
  <% end %>
  </div> <!--col-md-8-->
</div> <!--row-->

app/views/orders/done.html.erb
<h2> Thanks for your order </h2>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

<%= link_to 'Back', listing_orders_path(@listing) %>



<script src="https://js.stripe.com/v3/"></script>
<script>
var stripe = Stripe('pk_test_VvHAd5GiVkBsEKTpWHa4GpMo00LCb6dcSW');

 
    stripe.redirectToCheckout({
    sessionId: '<%= @stripe_checkout_session.id %>', // checkout ID is throwing an error
    }).then(function (result) {
    // If `redirectToCheckout` fails due to a browser or network
    // error, display the localized error message to your customer
    // using `result.error.message`.
    });

</script>

app/views/orders/purchases.html.erb
<div class="center">
    <h2>Your purchases history </h2>
</div>
    <table class="table table-striped table-bordered">
    <tr>
        <th>Image</th>
        <th>Item</th> 
        <th>Price</th>
        <th>Seller</th>
        <th>Date Purchased</th>
    </tr>

        <% @orders.each do |order| %>
            <%if order.listing %>
                <tr>
                    <td class="center"> <%= image_tag order.listing.thumbnail %></td>
                    <td class="center"> <%= order.listing.name %></td>
                    <td class="center"> <%= number_to_currency(order.listing.price) %></td>
                    <td class="center"> <%= order.seller.name %></td>
                    <td class="center"><%= order.created_at.strftime("%-d, %B, %Y") %></td> <!-- Used Ruby time function and formatted to day, month year as in Australia-->
                </tr>
            <%end%>
        <% end %>
    <table>
</div>

app/views/orders/sales.html.erb
<div class="center">
    <h2>Your sales history </h2>
</div>
    <table class="table table-striped table-bordered">
    <tr>
        <th>Image</th>
        <th>Item</th> 
        <th>Price</th>
        <th>Customer</th>
        <th>Date Sold</th>
    </tr>

        <% @orders.each do |order| %>
            <%if order.listing %>
            <tr>
                <td class="center"> <%= image_tag order.listing.thumbnail %></td>
                <td class="center"> <%= order.listing.name %></td>
                <td class="center"> <%= number_to_currency(order.listing.price) %></td>
                <td class="center"> <%= order.buyer.name %></td>
                <td class="center"><%= order.created_at.strftime("%-d, %B, %Y") %></td> <!-- Used Ruby time function and formatted to day, month year as in Australia-->
            </tr>
        <% end %>
        <% end %>
    <table>