config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/about'
  get 'pages/contact'
  root 'listings#index'#sets root file to all listings
  get 'seller' => 'listings#seller' #creates a new url at localhost/seller
  get 'sales' => "orders#sales" #set up new url for sales to see order history
  get 'purchases' => "orders#purchases" #set up new url for purchases to see order history
  get 'success', to: 'orders#done'
  

  resources :listings do #tell rails to include listing id number in URL for orders pages
  resources :orders, only: [:new, :create] #tells rails that only URLS it needs to worry about when it comes to orders is for new and create actions
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<p>Copyright 2019</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Made for China</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     
  
      </ul>
         <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Seller Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Manage Listings", seller_path, class: "nav-link" %>
            <%= link_to "Sales History", sales_path, class: "nav-link" %>
        </div> 

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %> <!-- Display current users name -->
          </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Purchases History", purchases_path, class: "nav-link" %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </div> 
            
        
        
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
        <li><%= link_to "Sign In", new_user_session_path, class: "nav-link" %></li>
      <% end %>
    </ul>
    </div> 
</nav>






<% if false %>

<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Marketplace</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "About", pages_about_path %></li>
      <li><%= link_to "Contact", pages_contact_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketplace</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body> 

<div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'layouts/header' %>

    <%= yield %>

    <%= render 'layouts/footer' %>
    
</div>

</body>
</html>